// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protoc/stream.proto

package protocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dkp           string                 `protobuf:"bytes,1,opt,name=dkp,proto3" json:"dkp,omitempty"`       // corresponds to DKP
	Colors        []string               `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty"` // corresponds to Colors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protoc_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protoc_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetDkp() string {
	if x != nil {
		return x.Dkp
	}
	return ""
}

func (x *Request) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

type Variant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seller         string                 `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	SellerId       int32                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Price          int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	VarWiner       bool                   `protobuf:"varint,4,opt,name=var_winer,json=varWiner,proto3" json:"var_winer,omitempty"`
	BuyBoxSellerId int32                  `protobuf:"varint,5,opt,name=buy_box_seller_id,json=buyBoxSellerId,proto3" json:"buy_box_seller_id,omitempty"`
	Promotion      bool                   `protobuf:"varint,6,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_protoc_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_protoc_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Variant) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *Variant) GetSellerId() int32 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *Variant) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Variant) GetVarWiner() bool {
	if x != nil {
		return x.VarWiner
	}
	return false
}

func (x *Variant) GetBuyBoxSellerId() int32 {
	if x != nil {
		return x.BuyBoxSellerId
	}
	return 0
}

func (x *Variant) GetPromotion() bool {
	if x != nil {
		return x.Promotion
	}
	return false
}

type ExtProductPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Variants      map[string]*Variants   `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuyBoxPrice   int32                  `protobuf:"varint,3,opt,name=buy_box_price,json=buyBoxPrice,proto3" json:"buy_box_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtProductPrice) Reset() {
	*x = ExtProductPrice{}
	mi := &file_protoc_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtProductPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtProductPrice) ProtoMessage() {}

func (x *ExtProductPrice) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtProductPrice.ProtoReflect.Descriptor instead.
func (*ExtProductPrice) Descriptor() ([]byte, []int) {
	return file_protoc_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ExtProductPrice) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExtProductPrice) GetVariants() map[string]*Variants {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *ExtProductPrice) GetBuyBoxPrice() int32 {
	if x != nil {
		return x.BuyBoxPrice
	}
	return 0
}

type Variants struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Variant             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // workaround for map<string, repeated Variant>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variants) Reset() {
	*x = Variants{}
	mi := &file_protoc_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variants) ProtoMessage() {}

func (x *Variants) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variants.ProtoReflect.Descriptor instead.
func (*Variants) Descriptor() ([]byte, []int) {
	return file_protoc_stream_proto_rawDescGZIP(), []int{3}
}

func (x *Variants) GetItems() []*Variant {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_protoc_stream_proto protoreflect.FileDescriptor

const file_protoc_stream_proto_rawDesc = "" +
	"\n" +
	"\x13protoc/stream.proto\x12\vpriceStream\"3\n" +
	"\aRequest\x12\x10\n" +
	"\x03dkp\x18\x01 \x01(\tR\x03dkp\x12\x16\n" +
	"\x06colors\x18\x02 \x03(\tR\x06colors\"\xba\x01\n" +
	"\aVariant\x12\x16\n" +
	"\x06seller\x18\x01 \x01(\tR\x06seller\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x05R\bsellerId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1b\n" +
	"\tvar_winer\x18\x04 \x01(\bR\bvarWiner\x12)\n" +
	"\x11buy_box_seller_id\x18\x05 \x01(\x05R\x0ebuyBoxSellerId\x12\x1c\n" +
	"\tpromotion\x18\x06 \x01(\bR\tpromotion\"\xe9\x01\n" +
	"\x0fExtProductPrice\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12F\n" +
	"\bvariants\x18\x02 \x03(\v2*.priceStream.ExtProductPrice.VariantsEntryR\bvariants\x12\"\n" +
	"\rbuy_box_price\x18\x03 \x01(\x05R\vbuyBoxPrice\x1aR\n" +
	"\rVariantsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.priceStream.VariantsR\x05value:\x028\x01\"6\n" +
	"\bVariants\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.priceStream.VariantR\x05items2V\n" +
	"\fPriceService\x12F\n" +
	"\fStreamPrices\x12\x14.priceStream.Request\x1a\x1c.priceStream.ExtProductPrice(\x010\x01B0Z.github.com/eslami200117/ala_unlimited/protocpbb\x06proto3"

var (
	file_protoc_stream_proto_rawDescOnce sync.Once
	file_protoc_stream_proto_rawDescData []byte
)

func file_protoc_stream_proto_rawDescGZIP() []byte {
	file_protoc_stream_proto_rawDescOnce.Do(func() {
		file_protoc_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_stream_proto_rawDesc), len(file_protoc_stream_proto_rawDesc)))
	})
	return file_protoc_stream_proto_rawDescData
}

var file_protoc_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protoc_stream_proto_goTypes = []any{
	(*Request)(nil),         // 0: priceStream.Request
	(*Variant)(nil),         // 1: priceStream.Variant
	(*ExtProductPrice)(nil), // 2: priceStream.ExtProductPrice
	(*Variants)(nil),        // 3: priceStream.Variants
	nil,                     // 4: priceStream.ExtProductPrice.VariantsEntry
}
var file_protoc_stream_proto_depIdxs = []int32{
	4, // 0: priceStream.ExtProductPrice.variants:type_name -> priceStream.ExtProductPrice.VariantsEntry
	1, // 1: priceStream.Variants.items:type_name -> priceStream.Variant
	3, // 2: priceStream.ExtProductPrice.VariantsEntry.value:type_name -> priceStream.Variants
	0, // 3: priceStream.PriceService.StreamPrices:input_type -> priceStream.Request
	2, // 4: priceStream.PriceService.StreamPrices:output_type -> priceStream.ExtProductPrice
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protoc_stream_proto_init() }
func file_protoc_stream_proto_init() {
	if File_protoc_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_stream_proto_rawDesc), len(file_protoc_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_stream_proto_goTypes,
		DependencyIndexes: file_protoc_stream_proto_depIdxs,
		MessageInfos:      file_protoc_stream_proto_msgTypes,
	}.Build()
	File_protoc_stream_proto = out.File
	file_protoc_stream_proto_goTypes = nil
	file_protoc_stream_proto_depIdxs = nil
}
